In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
df = pd.read_csv("crmls_last_6_months 2.csv",low_memory = False)
df

,ViewYN,BasementYN,PoolPrivateYN,Latitude,Longitude,LivingArea,FireplacesTotal,CountyOrParish,AttachedGarageYN,ParkingTotal,...,BedroomsTotal,StateOrProvince,FireplaceYN,Stories,Levels,LotSizeArea,NewConstructionYN,HighSchoolDistrict,PostalCode,LotSizeSquareFeet
0,False,NaN,NaN,37.330858,-121.849610,1151.0,NaN,Santa Clara,True,0.0,...,8.0,CA,True,NaN,NaN,6418.0,False,Other,95122,6418.0
1,True,NaN,False,34.180411,-118.342020,1434.0,NaN,Los Angeles,False,1.0,...,3.0,CA,True,1.0,One,6473.0,False,Burbank Unified,91505,6473.0
2,False,NaN,False,32.574359,-117.023836,2872.0,NaN,San Diego,True,6.0,...,5.0,CA,True,2.0,Two,5219.0,False,NaN,92154,5219.0
3,True,True,False,37.116859,-122.113773,800.0,NaN,Santa Cruz,False,8.0,...,2.0,CA,False,NaN,NaN,61649.0,False,Other,95006,61649.0
4,True,NaN,False,33.725080,-117.222302,2824.0,NaN,Riverside,True,2.0,...,5.0,CA,False,2.0,Two,7000.0,True,Mendocino Unified,92586,7000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61859,False,NaN,False,33.943555,-118.285762,1014.0,NaN,Los Angeles,False,1.0,...,2.0,CA,False,1.0,One,4225.0,False,Los Angeles Unified,90044,4225.0
61860,True,NaN,False,33.731745,-116.728918,648.0,NaN,Riverside,NaN,4.0,...,0.0,CA,True,NaN,NaN,8712.0,False,NaN,92549,8712.0
61861,False,NaN,False,34.264846,-118.426665,944.0,NaN,Los Angeles,False,2.0,...,3.0,CA,False,1.0,One,6750.0,False,Los Angeles Unified,91331,6750.0
61862,True,NaN,True,33.834420,-116.548440,4867.0,NaN,Riverside,True,4.0,...,5.0,CA,True,NaN,NaN,23087.0,False,NaN,92262,23087.0
61863,False,NaN,NaN,37.681503,-120.931510,2779.0,NaN,Stanislaus,True,3.0,...,5.0,CA,True,NaN,NaN,6600.0,False,Other,95355,6600.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61864 entries, 0 to 61863
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ViewYN                 56484 non-null  object
 1   BasementYN             1485 non-null   object
 2   PoolPrivateYN          56453 non-null  object
 3   Latitude               61864 non-null  float64
 4   Longitude              61864 non-null  float64
 5   LivingArea             61828 non-null  float64
 6   FireplacesTotal        0 non-null      float64
 7   CountyOrParish         61864 non-null  object
 8   AttachedGarageYN       54607 non-null  object
 9   ParkingTotal           61864 non-null  float64
 10  LotSizeAcres           60738 non-null  float64
 11  YearBuilt              61807 non-null  float64
 12  StreetNumberNumeric    61792 non-null  float64
 13  BathroomsTotalInteger  61855 non-null  float64
 14  City                   61808 non-null  object
 15  BedroomsTotal          61864 non-null  float64
 16  StateOrProvince        61864 non-null  object
 17  FireplaceYN            61826 non-null  object
 18  Stories                54290 non-null  float64
 19  Levels                 56438 non-null  object
 20  LotSizeArea            60744 non-null  float64
 21  NewConstructionYN      57362 non-null  object
 22  HighSchoolDistrict     45492 non-null  object
 23  PostalCode             61864 non-null  object
 24  LotSizeSquareFeet      60742 non-null  float64
dtypes: float64(13), object(12)
memory usage: 11.8+ MB

In [4]:
# df = df[(df.get('PropertyType') == 'Residential') & (df.get('PropertySubType') == 'SingleFamilyResidence')]
# df

In [5]:
Q1_LivingArea = df.get('LivingArea').quantile(0.25)
Q1_LivingArea

1379.0

In [6]:
Q3_LivingArea = df.get('LivingArea').quantile(0.75)
Q3_LivingArea

2421.0

In [7]:
IQR_LivingArea = Q3_LivingArea - Q1_LivingArea
IQR_LivingArea

1042.0

In [8]:
#no living area outlier
df = df[(df.get('LivingArea') >= Q1_LivingArea - 1.5*IQR_LivingArea) & (df.get('LivingArea') <= Q3_LivingArea+1.5*IQR_LivingArea)]
df

,ViewYN,BasementYN,PoolPrivateYN,Latitude,Longitude,LivingArea,FireplacesTotal,CountyOrParish,AttachedGarageYN,ParkingTotal,...,BedroomsTotal,StateOrProvince,FireplaceYN,Stories,Levels,LotSizeArea,NewConstructionYN,HighSchoolDistrict,PostalCode,LotSizeSquareFeet
0,False,NaN,NaN,37.330858,-121.849610,1151.0,NaN,Santa Clara,True,0.0,...,8.0,CA,True,NaN,NaN,6418.0,False,Other,95122,6418.0
1,True,NaN,False,34.180411,-118.342020,1434.0,NaN,Los Angeles,False,1.0,...,3.0,CA,True,1.0,One,6473.0,False,Burbank Unified,91505,6473.0
2,False,NaN,False,32.574359,-117.023836,2872.0,NaN,San Diego,True,6.0,...,5.0,CA,True,2.0,Two,5219.0,False,NaN,92154,5219.0
3,True,True,False,37.116859,-122.113773,800.0,NaN,Santa Cruz,False,8.0,...,2.0,CA,False,NaN,NaN,61649.0,False,Other,95006,61649.0
4,True,NaN,False,33.725080,-117.222302,2824.0,NaN,Riverside,True,2.0,...,5.0,CA,False,2.0,Two,7000.0,True,Mendocino Unified,92586,7000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61858,True,NaN,False,37.319615,-119.551230,1811.0,NaN,Madera,NaN,0.0,...,4.0,CA,True,2.0,Two,13068.0,False,Yosemite Unified,93604,13068.0
61859,False,NaN,False,33.943555,-118.285762,1014.0,NaN,Los Angeles,False,1.0,...,2.0,CA,False,1.0,One,4225.0,False,Los Angeles Unified,90044,4225.0
61860,True,NaN,False,33.731745,-116.728918,648.0,NaN,Riverside,NaN,4.0,...,0.0,CA,True,NaN,NaN,8712.0,False,NaN,92549,8712.0
61861,False,NaN,False,34.264846,-118.426665,944.0,NaN,Los Angeles,False,2.0,...,3.0,CA,False,1.0,One,6750.0,False,Los Angeles Unified,91331,6750.0
61863,False,NaN,NaN,37.681503,-120.931510,2779.0,NaN,Stanislaus,True,3.0,...,5.0,CA,True,NaN,NaN,6600.0,False,Other,95355,6600.0

In [9]:
df['LivingArea'].isna().sum()

0

In [10]:
df['AttachedGarageYN'].isna().sum()

6864

In [11]:
#fill the missing value with False
df['AttachedGarageYN']=df['AttachedGarageYN'].fillna(False)
df

/var/folders/xv/h3hzltmx43j1nxcddwpzsqpr0000gp/T/ipykernel_34103/2741110643.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['AttachedGarageYN']=df['AttachedGarageYN'].fillna(False)
/var/folders/xv/h3hzltmx43j1nxcddwpzsqpr0000gp/T/ipykernel_34103/2741110643.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AttachedGarageYN']=df['AttachedGarageYN'].fillna(False)

,ViewYN,BasementYN,PoolPrivateYN,Latitude,Longitude,LivingArea,FireplacesTotal,CountyOrParish,AttachedGarageYN,ParkingTotal,...,BedroomsTotal,StateOrProvince,FireplaceYN,Stories,Levels,LotSizeArea,NewConstructionYN,HighSchoolDistrict,PostalCode,LotSizeSquareFeet
0,False,NaN,NaN,37.330858,-121.849610,1151.0,NaN,Santa Clara,True,0.0,...,8.0,CA,True,NaN,NaN,6418.0,False,Other,95122,6418.0
1,True,NaN,False,34.180411,-118.342020,1434.0,NaN,Los Angeles,False,1.0,...,3.0,CA,True,1.0,One,6473.0,False,Burbank Unified,91505,6473.0
2,False,NaN,False,32.574359,-117.023836,2872.0,NaN,San Diego,True,6.0,...,5.0,CA,True,2.0,Two,5219.0,False,NaN,92154,5219.0
3,True,True,False,37.116859,-122.113773,800.0,NaN,Santa Cruz,False,8.0,...,2.0,CA,False,NaN,NaN,61649.0,False,Other,95006,61649.0
4,True,NaN,False,33.725080,-117.222302,2824.0,NaN,Riverside,True,2.0,...,5.0,CA,False,2.0,Two,7000.0,True,Mendocino Unified,92586,7000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61858,True,NaN,False,37.319615,-119.551230,1811.0,NaN,Madera,False,0.0,...,4.0,CA,True,2.0,Two,13068.0,False,Yosemite Unified,93604,13068.0
61859,False,NaN,False,33.943555,-118.285762,1014.0,NaN,Los Angeles,False,1.0,...,2.0,CA,False,1.0,One,4225.0,False,Los Angeles Unified,90044,4225.0
61860,True,NaN,False,33.731745,-116.728918,648.0,NaN,Riverside,False,4.0,...,0.0,CA,True,NaN,NaN,8712.0,False,NaN,92549,8712.0
61861,False,NaN,False,34.264846,-118.426665,944.0,NaN,Los Angeles,False,2.0,...,3.0,CA,False,1.0,One,6750.0,False,Los Angeles Unified,91331,6750.0
61863,False,NaN,NaN,37.681503,-120.931510,2779.0,NaN,Stanislaus,True,3.0,...,5.0,CA,True,NaN,NaN,6600.0,False,Other,95355,6600.0

In [12]:
df['AttachedGarageYN'].isna().sum()

0

In [13]:
Q1_ParkingTotal = df.get('ParkingTotal').quantile(0.25)
Q1_ParkingTotal

2.0

In [14]:
Q3_ParkingTotal = df.get('ParkingTotal').quantile(0.75)
Q3_ParkingTotal

3.0

In [15]:
IQR_ParkingTotal = Q3_ParkingTotal - Q1_ParkingTotal
IQR_ParkingTotal

1.0

In [16]:
#no parking total outlier
df = df[(df.get('ParkingTotal') >= Q1_ParkingTotal - 1.5*IQR_ParkingTotal) & (df.get('ParkingTotal') <= Q3_ParkingTotal+1.5*IQR_ParkingTotal)]
df

,ViewYN,BasementYN,PoolPrivateYN,Latitude,Longitude,LivingArea,FireplacesTotal,CountyOrParish,AttachedGarageYN,ParkingTotal,...,BedroomsTotal,StateOrProvince,FireplaceYN,Stories,Levels,LotSizeArea,NewConstructionYN,HighSchoolDistrict,PostalCode,LotSizeSquareFeet
1,True,NaN,False,34.180411,-118.342020,1434.0,NaN,Los Angeles,False,1.0,...,3.0,CA,True,1.0,One,6473.0,False,Burbank Unified,91505,6473.0
4,True,NaN,False,33.725080,-117.222302,2824.0,NaN,Riverside,True,2.0,...,5.0,CA,False,2.0,Two,7000.0,True,Mendocino Unified,92586,7000.0
5,True,NaN,False,34.203479,-118.643567,2500.0,NaN,Los Angeles,True,2.0,...,5.0,CA,True,2.0,Two,8336.0,False,Call Listing Office,91307,8336.0
6,False,NaN,False,34.460368,-118.490755,2363.0,NaN,Los Angeles,True,2.0,...,5.0,CA,True,2.0,Two,11705.0,False,William S. Hart Union,91390,11705.0
7,False,NaN,NaN,34.043218,-118.519477,3338.0,NaN,Los Angeles,False,2.0,...,4.0,CA,True,2.0,Two,6502.0,False,NaN,90272,6502.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61857,True,NaN,True,34.115293,-116.319679,1869.0,NaN,San Bernardino,True,2.0,...,3.0,CA,True,1.0,One,5.0,True,Morongo Unified,92252,217800.0
61859,False,NaN,False,33.943555,-118.285762,1014.0,NaN,Los Angeles,False,1.0,...,2.0,CA,False,1.0,One,4225.0,False,Los Angeles Unified,90044,4225.0
61860,True,NaN,False,33.731745,-116.728918,648.0,NaN,Riverside,False,4.0,...,0.0,CA,True,NaN,NaN,8712.0,False,NaN,92549,8712.0
61861,False,NaN,False,34.264846,-118.426665,944.0,NaN,Los Angeles,False,2.0,...,3.0,CA,False,1.0,One,6750.0,False,Los Angeles Unified,91331,6750.0
61863,False,NaN,NaN,37.681503,-120.931510,2779.0,NaN,Stanislaus,True,3.0,...,5.0,CA,True,NaN,NaN,6600.0,False,Other,95355,6600.0

In [17]:
df['ParkingTotal'].isna().sum()

0

In [18]:
df.shape

(49962, 25)